In [1]:
import warnings
warnings.filterwarnings('ignore')
import pickle
import numpy as np
import pandas as pd
import json
from textblob import TextBlob
import nltk
from scipy import spatial
import torch
import spacy
en_nlp = spacy.load('en_core_web_sm')

## Convert Json to Pandas Dataframe

In [2]:
#Load the training Dataset
train = pd.read_csv("trainingDataset.csv")

In [3]:
train.shape

(1605, 6)

In [4]:
train.head(3)

date           title  category  \
0  21.04.2020    Barack Obama       NaN   
1  21.04.2020       Joe Biden       NaN   
2  21.04.2020  George W. Bush       NaN   

                                           link  \
0    https://en.wikipedia.org/wiki/Barack_Obama   
1       https://en.wikipedia.org/wiki/Joe_Biden   
2  https://en.wikipedia.org/wiki/George_W._Bush   

                                            abstract  \
0  Barack Hussein Obama II ( (listen); born Augus...   
1  Joseph Robinette Biden Jr. (; born November 20...   
2  George Walker Bush (born July 6, 1946) is an A...   

                                          paragraphs  
0  ['Barack Hussein Obama II ( (listen); born Aug...  
1  ['Joseph Robinette Biden Jr. (; born November ...  
2  ['George Walker Bush (born July 6, 1946) is an...

In [5]:
df = pd.read_csv("trainingDataset.csv")

## Create dictionary of sentence embeddings for faster computation

In [6]:
paras = list(df["abstract"].drop_duplicates().reset_index(drop= True))

In [7]:
len(paras)

1568

In [8]:
#Join using TextBlob
blob = TextBlob(" ".join(paras))
sentences = [item.raw for item in blob.sentences]

In [9]:
len(sentences)

1559

In [10]:
#Load the InferSent Sentence Embeddings V1 and V2
from models import InferSent
V = 2
MODEL_PATH = 'C:\\Users\\Shilpu\\NLPProject\\QuestionAnsweringSystem\\InferSent\\encoder\\infersent%s.pkl' % V
params_model = {'bsize': 64, 'word_emb_dim': 300, 'enc_lstm_dim': 2048,
                'pool_type': 'max', 'dpout_model': 0.0, 'version': V}
infersent = InferSent(params_model)
infersent.load_state_dict(torch.load(MODEL_PATH))

<All keys matched successfully>

In [11]:
#Load the GloVe embedding
W2V_PATH = 'InferSent/dataset/GloVe/glove.840B.300d.txt'
infersent.set_w2v_path(W2V_PATH)

In [12]:
#Build the vocabulary.
infersent.build_vocab(sentences, tokenize=True)

Found 6141(/7255) words with w2v vectors
Vocab size : 6141


In [13]:
#Build the dictionary embeddings
dict_embeddings = {}
for i in range(len(sentences)):
    print(sentences[i])
    dict_embeddings[sentences[i]] = infersent.encode([sentences[i]], tokenize=True)
    print( dict_embeddings[sentences[i]])

Barack Hussein Obama II ( (listen); born August 4, 1961) is an American politician and attorney who served as the 44th president of the United States from 2009 to 2017.
[[-0.02874381  0.04943122  0.20910737 ...  0.1316887   0.04436744
   0.11170954]]
Joseph Robinette Biden Jr. (; born November 20, 1942) is an American politician who served as the 47th vice president of the United States from 2009 to 2017 and represented Delaware in the U.S. Senate from 1973 to 2009.
[[0.01917268 0.05178139 0.21973753 ... 0.06421494 0.0845053  0.11733628]]
George Walker Bush (born July 6, 1946) is an American politician and businessman who served as the 43rd president of the United States from 2001 to 2009.
[[-0.02874381  0.04943122  0.16229874 ...  0.06349707  0.054673
   0.1077443 ]]
Donald John Trump (born June 14, 1946) is the 45th and current president of the United States.
[[-0.01994209  0.06318004  0.1411632  ...  0.02324948  0.08776435
   0.09802058]]
George Washington (February 22, 1732 – Decem

[[-0.00239139  0.052432    0.17491902 ...  0.07826648  0.07221488
   0.11393397]]
Glenn Thomas Jacobs (born April 26, 1967) is an American professional wrestler, actor, author, businessman, and politician.
[[-0.00765041  0.04943122  0.15700327 ...  0.02883284  0.07050837
   0.08509059]]
Ben Lewis Jones (born August 30, 1941) is an American actor, politician, playwright and essayist, best known for his role as Cooter Davenport in The Dukes of Hazzard.
[[-0.02874381  0.06461575  0.16083872 ...  0.03310979  0.1101112
   0.09663422]]
John Augustus Kelly Jr. (September 16, 1927 – November 7, 1992), known professionally as Jack Kelly, was an American film and television actor most noted for the role of "Bart Maverick" in the television series Maverick, which ran on ABC from 1957-62.
[[-0.02874381  0.14793836  0.18929248 ...  0.09758885  0.0775933
   0.10871954]]
Sheila James Kuehl (born February 9, 1941) is an American politician, former child actress, and currently the member of the Los Ang

[[-0.02874381  0.11506773  0.16565734 ...  0.08459042  0.0848108
   0.13762784]]
Jean Lapointe,  (born December 6, 1935) is a Quebecois-Canadian actor, comedian and singer as well as a former Canadian Senator.
[[0.05079743 0.09485228 0.17493756 ... 0.01017086 0.0423076  0.09344561]]
Alexandrine Latendresse (born April 30, 1984) was the New Democratic Party Member of Parliament for Louis-Saint-Laurent and was elected in the 2011 Canadian federal election.
[[0.02062606 0.04943122 0.16068846 ... 0.09338584 0.04070921 0.11247552]]
Susan Leblanc is a Canadian politician and actress who was elected to the Nova Scotia House of Assembly in the 2017 provincial election.
[[0.00389284 0.04943122 0.13245724 ... 0.08254571 0.13907476 0.10766938]]
Jean-Louis Roux,  (May 18, 1923 – November 28, 2013) was a Canadian politician, entertainer and playwright who was briefly the 26th Lieutenant Governor of Quebec.
[[-0.0266937   0.11887632  0.17233463 ...  0.03127833  0.11604699
   0.09844093]]
Lenore Eliz

[[-0.00926997  0.07433592  0.11863941 ...  0.05436023  0.1342958
   0.09925629]]
James Keith O'Neill Edwards, DFC (23 March 1920 – 7 July 1988) was an English comedy writer and actor on radio and television, best known as Pa Glum in Take It From Here and as headmaster "Professor" James Edwards in Whack-O!.
[[-0.00795411  0.16860749  0.18895619 ...  0.11158337  0.09250305
   0.10228392]]
Andrew Matthew William Faulds (1 March 1923 – 31 May 2000) was a British actor and politician.
[[-0.02874381  0.06878513  0.15691224 ...  0.01038966  0.06424592
   0.06902032]]
Richard Franklin (15 July 1948 – 11 July 2007) was an Australian  film director.
[[-0.00497419  0.04943122  0.1425344  ...  0.04837483  0.0659315
   0.06991857]]
James Gaddas (born 9 June 1960 in Ragworth, Stockton-on-Tees, County Durham) is an English actor best known for playing Governing Governor Neil Grayling in ITV's Bad Girls.
[[-0.00427608  0.1770997   0.17344311 ...  0.09489776  0.0672026
   0.0960303 ]]
Helen Griffin (19

[[0.04530294 0.11126038 0.21186602 ... 0.06769342 0.07396746 0.10148454]]
Mimi Chakraborty (born 11 February 1989) is an Indian actress and politician.
[[-0.0063203   0.04943122  0.19727132 ...  0.0344511   0.03483311
   0.03894014]]
Gourang Chakraborty (born 16 June 1950), better known by his stage name Mithun Chakraborty (informally referred to as Mithun Da), is an Indian film actor, singer, producer, writer, social worker, entrepreneur, television presenter and a former Rajya Sabha Member of Parliament.
[[0.0058172  0.1331805  0.20949285 ... 0.08181215 0.08321298 0.09915087]]
Usashi Chakraborty is a Bengali film actress.
[[-0.00657415  0.04943122  0.23271789 ... -0.01258784 -0.04181507
   0.04470096]]
Honnasandra Narasimhaiah Chandrashekar, known popularly as Mukhyamantri Chandru (born 28 August 1953), is an Indian actor and politician.
[[0.0095729  0.12391892 0.16018623 ... 0.01713533 0.04721598 0.07645848]]
Locket Chatterjee (born 4 December 1974) is a Bengali actress, Indian poli

[[0.00064908 0.04943122 0.17378697 ... 0.11048505 0.13782457 0.09680593]]
Karunas (born 21 February 1970 as Karunanidhi Sethu) is an actor, politician and former comedian in the Tamil film industry.
[[0.03466563 0.08564319 0.1783108  ... 0.03167294 0.02933536 0.0895843 ]]
Vaishali Kasaravalli (12 April 1952 – 27 September 2010) was a noted Kannada actress, television serial director and costume designer.
[[-0.00819888  0.05820183  0.22788367 ...  0.153578    0.06777605
   0.08115222]]
Navaneet Kaur (also spelled Navneet Kaur; born 3 January 1986) is an Indian film actress who mainly acts in Telugu films.
[[0.0285932  0.04943122 0.22474009 ... 0.00727154 0.09818722 0.06788504]]
Kalvakuntla Kavitha (born 13 March 1978) is an Ex-MP and Telangana Rashtra Samithi party member.
[[0.03291486 0.19094123 0.16924055 ... 0.00340271 0.03562525 0.05139205]]
Arshi Khan is an Indian model, actress, internet celebrity and reality television personality.
[[0.02712034 0.04943122 0.19006583 ... 0.0659173

[[0.02082989 0.04943122 0.20460017 ... 0.10352176 0.04540205 0.07618142]]
Gul Panag (born Gulkirat Kaur Panag, 3 January 1979; Chandigarh, India) is an Indian actress, voice actress, model, and former beauty queen who competed in the Miss Universe pageant.
[[0.01672045 0.07154725 0.16120537 ... 0.02217497 0.04388314 0.0968562 ]]
Arun Pandian is an Indian film actor, director, producer and politician.
[[-0.00863239  0.04943122  0.17440394 ...  0.02510493  0.02637923
   0.12393663]]
Pandiyan (5 January 1959 – 10 January 2008) was an Indian actor and politician who acted in lead roles in about 75 Tamil films from 1983-1992 and supporting roles from 1993–2001.
[[0.00437645 0.04943122 0.24496607 ... 0.0996946  0.09484524 0.07974441]]
Chirag Paswan (born 31 October 1983) is an Indian politician and President of Lok Janshakti Party.
[[0.06198049 0.04943122 0.20418689 ... 0.01327533 0.0529415  0.12365244]]
Basavanagowda Channabasavanagowda Patil, popularly known as B. C. Patil, is a Kannada ac

[[0.04059608 0.06333873 0.18454681 ... 0.10293759 0.05781383 0.11175887]]
Divya Spandana (born 29 November 1982), who was known professionally as Ramya (Kannada: ರಮ್ಯಾ Ramyā), is an Indian film actress and politician who was the Member of Parliament in the Lok Sabha from Mandya,  Karnataka.
[[0.01720649 0.14892732 0.21827902 ... 0.0912158  0.04604523 0.0913658 ]]
Srinivasan (popularly known as Powerstar Srinivasan and sometimes simply Power) is an Indian actor and comedian, who has worked in the Tamil film industry.
[[0.03301792 0.12990661 0.20683765 ... 0.07790037 0.02361599 0.09422647]]
Sripriya is an Indian actress who played leading roles from 1973 to 1986.
[[-0.02874381  0.04943122  0.18413082 ...  0.037443    0.09605464
   0.10774904]]
Muthuvel Karunanidhi Stalin (born 1 March 1953) is an Indian politician from Tamil Nadu and Leader of opposition in the Tamil Nadu Legislative Assembly  from 25 May 2016.
[[0.06671187 0.04943122 0.18873374 ... 0.06053961 0.03071459 0.07586968]]
Uda

[[0.00106162 0.04943122 0.18138383 ... 0.06697772 0.08874159 0.10329164]]
Ronald Allan Kelley Poe (August 20, 1939 – December 14, 2004), better known as Fernando Poe Jr. and colloquially known as FPJ, Ronwaldo Reyes and Da King, was a Filipino actor, director and politician.
[[-0.01374097  0.2302466   0.10130683 ...  0.0937001   0.10999808
   0.11404771]]
Freddie Nelle Webb (born November 24, 1942) is a Filipino former senator, congressman, and basketball player and coach.
[[0.0067236  0.08798046 0.13923849 ... 0.07509826 0.04144353 0.08922174]]
Gary Jason B. Ejercito, better known as Gary Estrada, (born May 16, 1971) is a prolific television and movie actor in the Philippines.
[[0.03717607 0.13276081 0.23066477 ... 0.08211552 0.04420749 0.10217025]]
Emilio Ramon Pelayo Ejercito III (born October 5, 1963), commonly known as E.R.
[[0.04164342 0.10976217 0.15848847 ... 0.07937921 0.04456383 0.06255477]]
Guia Guanzon Gomez (born April 20, 1942) is a Filipino actress, businesswoman and pol

[[0.03962719 0.09587383 0.1597217  ... 0.05680071 0.05428649 0.11169994]]
Vandolph Lacsamana Quizon is a Filipino actor and comedian, known for being a councilor of the 1st District of Parañaque City.
[[-0.00809214  0.12292542  0.06052109 ...  0.0414119   0.08664816
   0.08022982]]
Maria Rosa Vilma Santos-Recto (born November 3, 1953) is a highly distinguished Filipino actress and politician.
[[-0.02110587  0.04943122  0.14805083 ...  0.05118854  0.10124609
   0.05118237]]
Rosalio D. Martires (born September 9, 1951), also known as Yoyong Martirez, is a Filipino retired basketball player, actor and comedian.
[[-0.00532362  0.07742067  0.15699875 ...  0.03770293  0.13265096
   0.09721504]]
Pahalage Rohitha Piyatissa Abeygunawardena (born 21 September 1966) is a Sri Lankan politician and businessman.
[[0.07315542 0.04943122 0.22917381 ... 0.02696186 0.0540152  0.07305031]]
Anarkali Akarsha (Sinhala: අනර්කලී ආකර්ෂා;born 12 July 1987,as Anarkali Janina Jayatilaka) is a Sri Lankan Film actr

[[-0.00497419  0.04943122  0.1413746  ...  0.0321615   0.11236788
   0.1013527 ]]
John George Diefenbaker   (; September 18, 1895 – August 16, 1979) was the 13th prime minister of Canada from 1957 to 1963.
[[-0.02874381  0.04943122  0.10735562 ...  0.02004178  0.0875431
   0.10713323]]
Charles Joseph "Joe" Clark  (born June 5, 1939) is a Canadian elder statesman, businessman, writer, and politician who served as the 16th prime minister of Canada, from June 4, 1979, to March 3, 1980.
[[-0.00519743  0.04943122  0.15133922 ...  0.07540538  0.06623975
   0.11343449]]
Martin Brian Mulroney  (; born March 20, 1939) is a Canadian politician who served as the 18th prime minister of Canada from September 17, 1984, to June 25, 1993.
[[-0.00505594  0.04943122  0.16096659 ...  0.04350395  0.05879967
   0.10565933]]
Avril Phaedra Douglas "Kim" Campbell  (born March 10, 1947) is a Canadian politician, diplomat, lawyer and writer who served as the 19th prime minister of Canada from June 25, 1993, to 

[[0.03030096 0.10789092 0.08442029 ... 0.06140999 0.08290233 0.1040277 ]]
Rodney Sturt Taylor (11 January 1930 – 7 January 2015) was an Australian-American actor.
[[-0.02874381  0.20348859  0.15978856 ...  0.03802858  0.05886397
   0.04161736]]
The Libertarian Party of Canada fielded a number of candidates in the 1980 federal election, none of whom were elected.
[[0.00663827 0.04943122 0.16547784 ... 0.04274904 0.02342948 0.0904502 ]]
Jonathan Neil Reynolds (born 28 August 1980) is a British Labour and Co-operative politician and Shadow Secretary of State for Work and Pensions who has been the Member of Parliament (MP) for Stalybridge and Hyde since 2010.
[[-0.02874381  0.04943122  0.15133809 ...  0.105849    0.07069997
   0.13529673]]
Stanisław "Stan" Tymiński (Polish pronunciation: [staˈɲiswaf tɨˈmʲiɲskʲi]; born January 27, 1948) is a Canadian businessman of Polish origin, dealing in electronics and computers, and a sometime-politician in both Poland and Canada.
[[0.0834683  0.049431

[[0.0046373  0.04943122 0.14472982 ... 0.02208059 0.04775072 0.13407807]]
Sajjad Haider Karim (born 11 July 1970) is a British politician.
[[-0.0020392   0.04943122  0.16545542 ... -0.00953768  0.03780323
   0.05498966]]
Rikke Karlsson (born 29 April 1965) is a Danish politician and Member of the European Parliament (MEP) from Denmark.
[[0.06393515 0.04943122 0.14979756 ... 0.0372331  0.04133341 0.09985042]]
Karol Adam Karski (born May 13, 1966 in Warsaw) is a Polish politician, Quaestor of the European Parliament, and a former Vice-Minister of Foreign Affairs.
[[0.02880901 0.08229853 0.13897176 ... 0.04834222 0.10714475 0.11737825]]
Timothy John Robert Kirkhope, Baron Kirkhope of Harrogate (born 29 April 1945) is a British lawyer and politician, previously serving as Member of the European Parliament for Yorkshire and the Humber for the Conservative Party.
[[-0.02874381  0.08646664  0.17691304 ...  0.02426673  0.07158948
   0.09359433]]
Ryszard Antoni Legutko (Polish pronunciation: [ˈ

[[-0.01657162  0.10587502  0.13865873 ...  0.02902756  0.08751718
   0.09570096]]
Milan Cabrnoch (born 6 August 1962 in Čáslav) is a Czech physician and politician.
[[ 0.03601222  0.04943122  0.11317862 ... -0.00549283  0.06324252
   0.0991482 ]]
Martin John Callanan, Baron Callanan (born 8 August 1961) is a British Conservative Party politician and UK Government Minister.
[[-0.01925876  0.04943122  0.16695444 ...  0.0360256   0.04641251
   0.15307745]]
Giles Bryan Chichester (born 29 July 1946) is a British Conservative Party politician, and was a Member of the European Parliament (MEP) for South West England and Gibraltar before retiring in 2014.
[[-0.02874381  0.08687242  0.16123104 ...  0.08280583  0.0883398
   0.11765074]]
Professor Isabella 'Susy' De Martini (born 17 June 1952 in Genoa) is an Italian politician and academic.
[[0.00214387 0.04943122 0.12916867 ... 0.07301386 0.08387959 0.05227333]]
James Edmund Moncrieff Elles (born 3 September 1949 in London) is a former Conserva

[[0.0150003  0.08904305 0.15642163 ... 0.06046507 0.11255282 0.15771322]]
Margaret Hilda Thatcher, Baroness Thatcher,  (née Roberts; 13 October 1925 – 8 April 2013) was a British stateswoman who served as prime minister of the United Kingdom from 1979 to 1990 and leader of the Conservative Party from 1975 to 1990.
[[-0.02874381  0.09777086  0.16084026 ...  0.02880958  0.06015786
   0.15603356]]
Sir John Major  (born 29 March 1943) is a British politician who served as Prime Minister of the United Kingdom and Leader of the Conservative Party from 1990 to 1997.
[[0.02231048 0.04943122 0.15459502 ... 0.03845977 0.08443515 0.16744506]]
William Jefferson Hague, Baron Hague of Richmond,  (born 26 March 1961) is a British Conservative politician and life peer.
[[-0.02874381  0.04943122  0.15246332 ...  0.00901663  0.06525778
   0.09526135]]
Michael Howard, Baron Howard of Lympne,  (born 7 July 1941), is a British politician who served as Leader of the Conservative Party and Leader of the Oppo

[[0.02524981 0.06705726 0.19674437 ... 0.03548291 0.12739873 0.07003703]]
Velikkakathu Sankaran Achuthanandan (born 20 October 1923) is a veteran Indian politician who was Chief Minister of Kerala from 2006 to 2011.
[[0.05401888 0.04943122 0.2138521  ... 0.04768842 0.04781594 0.09251795]]
Shri Edappakath Ahamed (29 April 1938 – 1 February 2017) was an Indian politician who served as Minister of State for External Affairs in the Manmohan Singh government (2004–14).
[[0.00939186 0.04943122 0.17772888 ... 0.08138631 0.04111319 0.1264596 ]]
K. R. Gowri Amma (born 14 July 1919) is an Indian politician from Kerala.
[[-0.00364146  0.04943122  0.22164848 ...  0.0221799   0.04155783
   0.03140954]]
Arackaparambil Kurien Antony, better known as A. K. Antony (born 28 December 1940) is an Indian politician and attorney who was the 23rd Defence Minister of India and he was also the Chief Minister of Kerala.
[[-0.02874381  0.09261189  0.22808546 ...  0.0556784   0.0903616
   0.13100213]]
E. Balanand

[[0.09240471 0.04943122 0.16426831 ... 0.02561383 0.05872133 0.07355254]]
Kocheril Raman Narayanan (listen ); (4 February 1921 – 9 November 2005) was the tenth President of India and ninth Vice President of IndiaBorn in Perumthanam, Uzhavoor village, in the princely state of Travancore (present day Kottayam district, Kerala), and after a brief stint with journalism and then studying political science at the London School of Economics with the assistance of a scholarship, Narayanan began his career in India as a member of the Indian Foreign Service in the Nehru administration.
[[0.04577988 0.10941993 0.18245651 ... 0.12100054 0.06704295 0.11375736]]
Lal Krishna Advani (born 8 November 1927) is an Indian politician who served as the 7th Deputy Prime Minister of India from 2002 to 2004 under Atal Bihari Vajpayee.
[[0.07485078 0.04943122 0.22336257 ... 0.01715611 0.05527248 0.14943574]]
Rahul Gandhi (pronunciation  [ˈraːɦʊl ˈɡaːnd̪ʱiː]) (born 19 June 1970) is an Indian politician who was t

[[0.10196882 0.08765456 0.16891648 ... 0.01898206 0.05036824 0.07521129]]
Kalikesh Narayan Singh Deo (born 26 May 1974) is an Indian politician who was Member of Parliament in the Lok Sabha from Bolangir and member and leader of the Biju Janata Dal political party.His father, Ananga Udaya Singh Deo, and his grandfather, Rajendra Narayan Singh Deo, were both politicians.
[[0.04801165 0.09097114 0.22728828 ... 0.12364884 0.09001219 0.1109304 ]]
Gautam Gambhir (pronunciation ; born 14 October 1981) is an Indian politician and former cricketer, who has played all formats of the game.
[[0.09571853 0.07327032 0.1607182  ... 0.09734061 0.04423532 0.09750283]]
Sachin Ramesh Tendulkar ( (listen); born 24 April 1973) is an Indian former international cricketer and a former captain of the Indian national team.
[[0.1152769  0.08382828 0.15993002 ... 0.095024   0.02406765 0.09324437]]
Aslam Sher Khan (born 15 July 1953) is an Indian hockey player and a former member of the Indian team.
[[0.06645432

[[0.00926406 0.09447552 0.19436772 ... 0.04630368 0.05415086 0.11123071]]
Tsuneo Horiuchi (堀内 恒夫, Horiuchi Tsuneo, born January 16, 1948, in Kōfu, Yamanashi) is a former professional baseball player in Japan's Nippon Professional Baseball, and a politician.
[[0.01589916 0.09082154 0.19224092 ... 0.00758546 0.09313754 0.14533204]]
Muhammad Hussain Inoki (ムハンマド・フセイン・イノキ, Muhanmado Fusein Inoki) (Arabic: مُحَمَّد حُسَيْن إينوكي‎, romanized: Muḥammad Ḥusayn ʻIinuki; born Kanji Inoki (猪木寛至, Inoki Kanji) on February 20, 1943) is a Japanese professional wrestling and mixed martial arts promoter, and retired professional wrestler, martial artist, and politician.
[[0.04338384 0.06267752 0.21076721 ... 0.14005494 0.05720817 0.08509059]]
Kunishige Kamamoto (釜本 邦茂, Kamamoto Kunishige, born April 15, 1944) is a former Japanese football player, manager and politician.
[[0.03711271 0.08751005 0.14575912 ... 0.04650037 0.04370787 0.12448418]]
Shinobu Kandori (神取 忍, Kandori Shinobu, born October 30, 19

[[-0.0043008   0.08281049  0.19864683 ...  0.10572099  0.04037551
   0.08100128]]
Ambrosio Bibby Padilla (December 7, 1910 – August 11, 1996) was a Filipino basketball player and an elected member of the Senate of the Philippines.
[[-0.02874381  0.10499295  0.17340131 ...  0.06580596  0.07523114
   0.12449758]]
Franz S. Pumaren is a Filipino former professional basketball player and coach.
[[-0.02874381  0.09835932  0.14588428 ...  0.04316876  0.10013406
   0.08863778]]
Michael Odylon "Mikee" Lagman Romero (born March 21, 1972) is a Filipino businessman, politician, and sportsman serving as a Party-list Representative for 1-Pacman since 2016.
[[0.02861773 0.04943122 0.16526167 ... 0.02515749 0.06041045 0.10158969]]
Christopher John Alandy-Dy Tiu (born on July 15, 1985) is Filipino former professional basketball player and television personality.
[[0.01333171 0.08349073 0.16759446 ... 0.06591732 0.04756493 0.09922815]]
Simeon Galvez Toribio (September 3, 1905 – June 5, 1969) was a Filip

[[0.01109621 0.04943122 0.16815096 ... 0.08534263 0.0864187  0.05775146]]
Konstadinos "Kostas" Koukodimos (Greek: Κωνσταντίνος "Κώστας" Κουκοδήμος, born 14 September 1969 in Melbourne) is a retired Greek long jumper and New Democracy politician, currently serving as the mayor of Katerini, Macedonia.
[[0.02652525 0.04943122 0.16951299 ... 0.06965405 0.06014857 0.10132864]]
Elena Kountoura (Greek: Έλενα Κουντουρά, also romanized as Elena Koundoura; born 2 November 1962), is a Greek politician, Member of the European Parliament, ex-Minister of Tourism (resigned on May 3, 2019 in order to participate in the European Parliament's elections) in the Cabinet of Alexis Tsipras, and Member of Parliament for Athens A, for the Independent Greeks, and earlier for New Democracy.
[[-0.01845285  0.04943122  0.12309678 ...  0.0743525   0.06715765
   0.10645289]]
Grigoris Lambrakis (Greek: Γρηγόρης Λαμπράκης; 3 April 1912 – 27 May 1963) was a Greek politician, physician, track and field athlete, and mem

[[-0.02874381  0.1571076   0.07575313 ...  0.09471912  0.05378573
   0.08187471]]
Kenneth "Kenny" Egan (born 7 January 1982) is an Irish politician and amateur boxer from Clondalkin, Dublin best known for winning a Silver Medal in the final of the 81 kg, Light-Heavyweight boxing final at the 2008 Olympics.
[[0.00444196 0.17453194 0.1668092  ... 0.05329672 0.0408128  0.09019316]]
James Alfred Ennis III (born July 1, 1990) is an American professional basketball player for the Orlando Magic of the National Basketball Association (NBA).
[[-0.02638456  0.04943122  0.1741356  ...  0.07361837  0.11906022
   0.08174613]]
Martin Ferris (born 28 March 1952) is a former Irish Sinn Féin politician and former Provisional Irish Republican Army (IRA) volunteer who served as a Teachta Dála (TD) from 2002 to 2020.
[[-0.01869436  0.23342443  0.14018652 ...  0.0923017   0.03789139
   0.15789309]]
David Finlay Jr. (born 31 January 1958) is a Northern Irish professional wrestling trainer, producer and reti

[[0.0150003  0.16398627 0.16105366 ... 0.04663188 0.1496873  0.10026701]]
Ian McGarvey (born July 1929) is a former association footballer and a politician who is Ireland's oldest public representative either side of the island's border.
[[-0.01376879  0.13216081  0.13146695 ...  0.08939973  0.12536459
   0.10598115]]
Joe McHugh (born 16 July 1971) is an Irish Fine Gael politician who has served as Minister for Education and Skills since October 2018.
[[0.01318011 0.04947904 0.18413636 ... 0.04906018 0.11497146 0.12002315]]
Justin McNulty MLA (born 15 November 1974) is an Irish Social Democratic and Labour Party (SDLP) politician, a former Gaelic football manager, and a former player for Armagh.
[[0.00876322 0.18444082 0.14694655 ... 0.04214931 0.04436385 0.12821822]]
John McQuillan (30 August 1920 – 8 March 1998) was an Irish politician, trade union official and army officer.
[[0.00369964 0.0652136  0.12083626 ... 0.02808403 0.04703143 0.11906987]]
Sir Henry George Hill Mulholland, 1s

[[0.00611043 0.04943122 0.12235823 ... 0.02025347 0.07482937 0.07756092]]
Ivar Egeberg (born 11 March 1950) is a Norwegian sports official, retired athlete and politician for the Centre Party.
[[ 0.01366241  0.11583488  0.16619243 ... -0.01258784  0.02896799
   0.08894253]]
Eilert Eilertsen (25 February 1918 – 24 February 2014) was a Norwegian footballer, physician and politician for the Conservative Party.
[[-0.01618307  0.11225713  0.15903391 ...  0.01309912  0.05905642
   0.09359433]]
Jon Fossum (23 February 1923 – 10 July 2007) was a Norwegian orienteer and politician for the Conservative Party.
[[0.022217   0.04943122 0.14848794 ... 0.01693113 0.05767579 0.09359433]]
Jan Gulbrandsen (29 May 1938 – 4 September 2007) was a Norwegian hurdler, politician and sports official.
[[0.0040374  0.04943122 0.15177895 ... 0.03855794 0.07727719 0.07871462]]
Arne Hamarsland (born 24 July 1933) is a Norwegian middle distance runner who specialized in 1500 metres.
[[0.03690885 0.16495787 0.1223251

[[0.05072128 0.13562311 0.16344067 ... 0.07462149 0.0971449  0.08572312]]
Vladislav Aleksandrovich Tretiak, MSM (Russian: Владислав Александрович Третьяк, IPA: [trʲɪˈtʲjak]; born 25 April 1952) is a Russian former goaltender for the Soviet Union national ice hockey team.
[[0.06551225 0.04943122 0.12146976 ... 0.0945597  0.05441687 0.10375204]]
Nikolai Sergeyevich Valuev (vah-LOO-yev, Russian: Никола́й Серге́евич Валу́ев, IPA: [vɐˈlujɪf]; born 21 August 1973) is a Russian politician and former professional boxer.
[[0.06253289 0.0610531  0.14197645 ... 0.09814829 0.04836393 0.07864233]]
Yury Petrovich Vlasov (Russian: Юрий Петрович Власов; born 5 December 1935) is a Soviet writer and retired heavyweight weightlifter and politician.
[[0.10720386 0.04943122 0.12111981 ... 0.031013   0.12729926 0.06546311]]
Alexey Ivanovich Voyevoda (Russian: Алексей Иванович Воевода; born 9 May 1980) is a Russian bobsledder and professional armwrestler.
[[0.06430198 0.1597949  0.17446652 ... 0.02783601 0.0

[[0.03497953 0.09926442 0.12970841 ... 0.08606707 0.10454812 0.12678269]]
Sir Reginald Frederick Brittain Bennett (b Sheffield 22 July 1911 – d London 19 December 2000) was an English Conservative Party politician, international yachtsman, psychiatrist and painter.
[[0.0150003  0.04943122 0.12477677 ... 0.05452892 0.11968327 0.09639852]]
William Henry Cavendish-Bentinck  (14 September 1774 – 17 June 1839), known as Lord William Bentinck, was a British soldier and statesman.
[[0.0883741  0.12703645 0.18812431 ... 0.04092888 0.15415055 0.09606345]]
This page list topics related to Malta.
[[0.04414479 0.04943122 0.08933968 ... 0.01734102 0.0426909  0.02417473]]
Christopher Bethell-Codrington (born Christopher Codrington; October 1764 – 4 February 1843) was a British Member of Parliament, owner of sugar plantations in the Caribbean, and English amateur cricketer.
[[0.00173176 0.04943122 0.13367756 ... 0.07728963 0.14689024 0.09690655]]
Sir Francis Christopher Buchan Bland (29 May 1938 – 28

[[0.0150003  0.04943122 0.1721286  ... 0.06614735 0.11358593 0.06205473]]
John Horton Conway  (26 December 1937 – 11 April 2020) was an English mathematician active in the theory of finite groups, knot theory, number theory, combinatorial game theory and coding theory.
[[-0.02874381  0.14260632  0.10893755 ...  0.06325177  0.09399306
   0.06692404]]
John Ambrose Cope, Baron Cope of Berkeley, PC (born 13 May 1937) is a Conservative Party politician in the United Kingdom.
[[-0.02874381  0.08498353  0.17531207 ...  0.10885814  0.11176462
   0.13119215]]
William Courtenay (c. 1342 – 31 July 1396) was Archbishop of Canterbury (1381-96), having previously been Bishop of Hereford and Bishop of London.
[[-0.02874381  0.09110425  0.21074945 ...  0.08564933  0.05652078
   0.079076  ]]
Michael Colin Cowdrey, Baron Cowdrey of Tonbridge,  (24 December 1932 – 4 December 2000) was an English first-class cricketer who played for Oxford University (1952–1954), Kent County Cricket Club (1950–1976) and E

[[-0.0252116   0.04943122  0.14331305 ...  0.04002851  0.12066469
   0.09465715]]
Clifford Forsythe (25 August 1929 – 27 April 2000) was a Northern Ireland Ulster Unionist Party politician.
[[-0.01293775  0.21206163  0.13967799 ...  0.02721156  0.06826055
   0.1248208 ]]
Walter Fowden (1878 – 21 May 1949) was a British politician and swimmer.
[[0.00190174 0.04943122 0.13073178 ... 0.00486681 0.07674654 0.07017542]]
Hew Thomson Fraser (25 July 1877 – 11 August 1938) was a Scottish field hockey player and British Liberal Party politician.
[[-0.00494077  0.10130472  0.09870949 ...  0.04674799  0.07818399
   0.12107487]]
Charles Burgess Fry (25 April 1872 – 7 September 1956) was an English sportsman, politician, diplomat, academic, teacher, writer, editor and publisher, who is best remembered for his career as a cricketer.
[[-0.00519743  0.04943122  0.11999483 ...  0.11414906  0.10918718
   0.10009098]]
William Fuller Maitland (1813–1876) was an English picture collector.
[[-0.00261802  0.

[[0.0150003  0.06858138 0.10853396 ... 0.03976423 0.18529414 0.09971803]]
Arthur Grey Hazlerigg, 2nd Baron Hazlerigg, MC, TD (24 February 1910 – 30 September 2002), was a British peer, cricketer, soldier and chartered surveyor.
[[-0.02874381  0.12242964  0.15538302 ...  0.02813308  0.09983613
   0.09881819]]
Arthur Howard Heath TD (29 May 1856 – 24 April 1930) was a British industrialist, first-class cricketer, Rugby Union international and Conservative Party politician.
[[-0.02874381  0.12873144  0.1817103  ...  0.01585409  0.105096
   0.11940835]]
Sir James Heath, 1st Baronet (26 January 1852 – 24 December 1942) was a businessman and Conservative Party politician in the United Kingdom.
[[0.0150003  0.05964785 0.14523192 ... 0.01288981 0.15825354 0.13119215]]
Edward George Hemmerde, KC (13 November 1871 – 24 May 1948) was an English rower, barrister, politician, and Georgist.
[[-0.02874381  0.06464366  0.16171731 ...  0.01553701  0.06767958
   0.08383013]]
John Maxwell Heron-Maxwell (

[[0.0395909  0.19699748 0.15170486 ... 0.10000959 0.06259566 0.11066991]]
David Lloyd George, 1st Earl Lloyd-George of Dwyfor,   (17 January 1863 – 26 March 1945) was a British statesman who served as Prime Minister of the United Kingdom from 1916 to 1922.
[[-0.02050338  0.07144633  0.15056719 ...  0.02070499  0.08425955
   0.15744685]]
Richard Penruddocke Long JP, DL (19 December 1825 – 16 February 1875) was an English landowner and Conservative Party politician.
[[0.10111313 0.04943122 0.14029075 ... 0.08572108 0.1141357  0.09925629]]
Henry Carpenter Longhurst (18 March 1909 – 21 July 1978) was a British golf writer and commentator.
[[-0.0252116   0.04943122  0.12590352 ...  0.01850881  0.07728636
   0.05026381]]
Robert Threshie Reid, 1st Earl Loreburn,  (3 April 1846 – 30 November 1923) was a British lawyer, judge and radical Liberal politician.
[[-0.0184001   0.08806878  0.130561   ...  0.0265506   0.09116653
   0.09015604]]
Percy Belgrave Lucas,  (2 September 1915 – 20 March 1998)

[[0.03065043 0.06409374 0.14125535 ... 0.03895409 0.15802252 0.06928661]]
William Benedict Nicholson, OBE, FRSL (born 12 January 1948) is a British screenwriter, playwright, and novelist who has been nominated twice for an Oscar.
[[-0.02435472  0.14557151  0.19601275 ...  0.04356183  0.0916905
   0.08246654]]
Philip John Noel-Baker, Baron Noel-Baker,  (1 November 1889 – 8 October 1982), born Philip John Baker, was a British politician, diplomat, academic, outstanding amateur athlete, and renowned campaigner for disarmament.
[[-0.02874381  0.07305459  0.16212085 ...  0.03557326  0.09215132
   0.09383278]]
Onslow County is a county located in the U.S. state of North Carolina.
[[0.15040833 0.12504518 0.2669227  ... 0.04640208 0.08245173 0.07371636]]
George Osbaldeston (26 December 1786 – 1 August 1866), best known as Squire Osbaldeston, was an English politician who served as a Member of Parliament but who had his greatest impact as a sportsman and first-class cricketer.
[[0.00454655 0.09

[[-0.0252116   0.06149898  0.13062909 ...  0.0487505   0.14818713
   0.09785997]]
Sir John Shelley, 6th Baronet (18 December 1771 – 28 March 1852) was an English landowner, Member of Parliament and amateur cricketer.
[[0.0150003  0.07175905 0.15676005 ... 0.01922146 0.14960203 0.09611466]]
Tommy Sheridan (born 7 March 1964) is a Scottish politician who was co-convenor of Solidarity, along with Rosemary Byrne until June 2016.
[[-0.00720762  0.11431086  0.11731204 ...  0.04772118  0.0936215
   0.09411731]]
Samuel Charles Silkin, Baron Silkin of Dulwich, PC, QC (6 March 1918 – 17 August 1988) was a British Labour Party politician and cricketer.
[[0.02653616 0.08034619 0.11393405 ... 0.02128274 0.13225898 0.14239317]]
Eric M. Smith (born January 22, 1980) is an American criminal who is incarcerated for the murder of four-year-old Derrick Robie (born October 2, 1988) on August 2, 1993 in Steuben County, New York.
[[0.00838961 0.09127229 0.17438045 ... 0.06325402 0.05597328 0.0686285 ]]
Bett

[[0.02124503 0.14858027 0.1721183  ... 0.08913524 0.08611494 0.13061598]]
Ernest "Ernie" Woodhead (2 February 1857 – 10 June 1944) was an English rugby union footballer who played in the 1880s.
[[0.00208049 0.04943122 0.10803601 ... 0.07208745 0.10420518 0.06383718]]
Henry Smith Wright (27 June 1839 – 19 March 1910) was an English barrister, banker and Conservative Party politician who sat in the House of Commons from 1885 to 1895.
[[-0.0252116   0.04943122  0.1231746  ...  0.08618189  0.10849922
   0.11376236]]
Derek Murray Wyatt FRSA (born 4 December 1949) is a British Labour Party politician who was the Member of Parliament (MP) for Sittingbourne and Sheppey from 1997 to 2010, having previously been a councillor in the London Borough of Haringey.
[[-0.01602206  0.08943747  0.15257667 ...  0.05693311  0.05197953
   0.14868322]]
Charles Griffith Wynne (14 August 1815 – 3 March 1874), later known as Charles Wynne-Finch, was a Liberal Tory politician and a Member of Parliament for Caern

   0.08674099]]
Nathan Joseph Harry Divinsky (October 29, 1925 – June 17, 2012) was a Canadian mathematician, university professor, chess master, chess writer, and chess official.
[[-0.02874381  0.04943122  0.14074948 ...  0.0555365   0.14754692
   0.07530601]]
Fin Donnelly (born May 27, 1966) is a Canadian politician, who was elected to the House of Commons of Canada to represent the electoral district of Port Moody—Coquitlam.
[[0.00101622 0.14552858 0.17912015 ... 0.07576886 0.05704466 0.12780389]]
Clive Doucet (born 1946) is a Canadian writer and politician.
[[-0.00909723  0.0827218   0.1453469  ...  0.02661849  0.04414212
   0.0883434 ]]
Kenneth Wayne Dryden, , (born August 8, 1947) is a Canadian politician, lawyer, businessman, author, and former National Hockey League (NHL) goaltender.
[[0.01581447 0.10314034 0.21150729 ... 0.01087029 0.0779533  0.10431251]]
Peter Stefan Dyakowski (born April 19, 1984) is a Canadian football offensive lineman who is currently a free agent.
[[0.02

[[-0.01186847  0.09801341  0.14697772 ...  0.03099932  0.10900423
   0.07357271]]
Kiviaq (also known as David Charles Ward; January 23, 1936 – April 24, 2016) was a Canadian Inuit lawyer, politician, and former sportsman.
[[0.03711271 0.10522368 0.1818147  ... 0.05557123 0.08227459 0.09320644]]
Fred Koe (born March 8, 1947) is a former territorial level politician and Member of the Legislative Assembly of the Northwest territories from 1991 to 1995.
[[0.01056352 0.08714505 0.1735885  ... 0.04056933 0.06195858 0.10377929]]
Helena Konanz (née Manset) is an American tennis player and Canadian politician.
[[0.0069941  0.08636163 0.13491951 ... 0.01484628 0.00863137 0.09850284]]
Jamie A. Korab, ONL (born November 28, 1979 in Harbour Grace, Newfoundland) is a Canadian curler and politician.
[[0.00021023 0.06452441 0.17780304 ... 0.03426895 0.10720098 0.0826301 ]]
Oskar Kruger (December 24, 1932 – July 4, 2010) was a defensive back for the Edmonton Eskimos from 1954 to 1965 of the Canadian Fo

[[-0.01074251  0.04943122  0.15255006 ...  0.0347078   0.06894989
   0.10396513]]
Steven Patrick Morrissey (; born 22 May 1959), known mononymously as Morrissey, is an English singer, songwriter, and author.
[[-0.00458806  0.11903206  0.19302207 ...  0.06038878  0.15981013
   0.07438052]]
Lester Bowles Pearson  (23 April 1897 – 27 December 1972) was a Canadian scholar, statesman, soldier, prime minister, and diplomat, who won the Nobel Peace Prize in 1957 for organizing the United Nations Emergency Force to resolve the Suez Canal Crisis.
[[-0.01409709  0.04943122  0.18466404 ...  0.10867395  0.10944606
   0.12583162]]
Janko Peric (born February 24, 1949), is a former Canadian politician.
[[ 0.05830542  0.08972192  0.17961124 ... -0.0047254   0.0440234
   0.08908438]]
Chantal Petitclerc,  (born December 15, 1969 in Saint-Marc-des-Carrières, Quebec) is a Canadian wheelchair racer and a Senator from Quebec.
[[0.06654034 0.12587275 0.14193569 ... 0.00996775 0.08027963 0.07755883]]
Robert H

[[-0.02764728  0.05784085  0.14342669 ...  0.02068079  0.14390697
   0.10985059]]
Larry Uteck (October 9, 1952 – December 25, 2002) was a Canadian professional football athlete, university sports administrator, football coach, and municipal politician.
[[0.00596439 0.08449998 0.1236954  ... 0.01984863 0.07270402 0.10216516]]
Daniel Vandal  (born April 18, 1960) is a Métis Canadian politician in Winnipeg, Manitoba, Canada.
[[-0.0266321   0.11814705  0.1625739  ...  0.01936511  0.04549186
   0.08428499]]
Fitzroy 'FITZ THE WHIP' Vanderpool is one of Canada’s most decorated professional champions holding 6 title belts.
[[0.00257661 0.21984962 0.15592611 ... 0.06360034 0.02521513 0.08480506]]
Cory E. Vanthuyne is a Canadian politician, who was elected to the Legislative Assembly of the Northwest Territories in the 2015 election.
[[-0.02874381  0.1185763   0.19886509 ...  0.00172814  0.04744721
   0.11326088]]
Nicholas Joseph Vinnicombe (January 14, 1877 – April 10, 1928) was a merchant and 

[[-0.00074208  0.11645331  0.16563722 ...  0.04186462  0.0627827
   0.1158315 ]]
Percy Brereton Colquhoun (28 September 1866 – 23 October 1936) was an Australian parliamentarian, lawyer and sportsman.
[[-0.02489645  0.16256551  0.16563281 ...  0.01810544  0.09939859
   0.06105245]]
Ephraim Henry Coombe (26 August 1858 – 5 April 1917) was a South Australian newspaper editor and politician.
[[-0.01152078  0.04943122  0.176165   ...  0.07581178  0.1185189
   0.05653145]]
Matthew John Cowdrey  (born 22 December 1988) is an Australian swimmer and politician.
[[-0.02874381  0.06351101  0.16805744 ... -0.00198655  0.04173584
   0.05686857]]
Joseph Darling CBE (21 November 1870 – 2 January 1946) was an Australian cricketer who played 34 Test matches as a specialist batsman between 1894 and 1905.
[[0.01744282 0.04943122 0.18117568 ... 0.09615719 0.08035624 0.08579214]]
Everard Firebrace Darlot (23 January 1859 – 5 November 1937) was an Australian pastoralist and politician who was a member of t

[[0.00986569 0.24306121 0.17375726 ... 0.06062459 0.08172729 0.1049096 ]]
Raymond John Groom  (born 3 September 1944) is an Australian lawyer and former sportsman and politician, representing the Liberal Party in the Federal Parliament 1975–84 and the Tasmanian Parliament 1986–2001.
[[-0.01902479  0.09136218  0.15747024 ...  0.01740777  0.04575717
   0.11228262]]
Arthur Courthope Gull (1 January 1867 – 30 March 1951) was an Australian politician who served as a member of the Legislative Assembly of Western Australia from 1905 to 1908, representing the seat of Swan.
[[-0.02874381  0.08790162  0.17276882 ...  0.03702656  0.0831563
   0.09880303]]
Damian Francis Hale (born 28 December 1969) is a former Australian Labor Party member of the Australian House of Representatives, representing the Division of Solomon from 2007 to 2010.
[[-0.02874381  0.08601423  0.17147167 ...  0.0893108   0.07898722
   0.10888416]]
Kevin Peter Hall (May 9, 1955 – April 10, 1991) was an American actor best know

[[-0.01271527  0.04943122  0.17422429 ...  0.08795337  0.05214209
   0.08535303]]
Mervyn William Lee (18 August 1920 – 13 December 2009) was an Australian politician who served as the Liberal member for Lalor from 1966 to 1969.
[[-0.02874381  0.12560484  0.14728457 ...  0.03604304  0.05841439
   0.11428427]]
Henry Elms Lette (christened 10 August 1829 – 15 August 1892) was an Australian cricketer and politician.
[[-0.0252116   0.04943122  0.15478297 ...  0.05033385  0.13193873
   0.05518048]]
Samuel John Everett Loxton, OBE (29 March 1921 – 3 December 2011) was an Australian cricketer, footballer and politician.
[[-0.0257474   0.04943122  0.14589854 ...  0.03965279  0.05419948
   0.0525537 ]]
Brendan Aloysius Lyons (17 June 1927 – 7 September 2010) was an  Australian politician who served in the Tasmanian House of Assembly from 1982 to 1986, representing the Liberal Party.
[[0.0038718  0.15897873 0.14325126 ... 0.10796357 0.07481238 0.10643383]]
Justin Mark Madden  (born 31 May 1961) i

[[-0.00885168  0.1506995   0.16554983 ...  0.11112928  0.14070082
   0.10678719]]
Maurice Joseph Rioli (1 September 1957 – 25 December 2010) was an Australian rules footballer who represented St Mary's Football Club in the Northern Territory Football League (NTFL), South Fremantle in the West Australian Football League (WAFL) and Richmond in the Victorian Football League.
[[0.00717647 0.1800903  0.1456698  ... 0.06063615 0.09293817 0.06966899]]
Gregory John Rowell (born 1 September 1966 in Lindfield, New South Wales) is an Australian cricket player, who has played for the Queensland Bulls, New South Wales Blues, and Tasmanian Tigers.
[[-0.0271304   0.1053493   0.22716396 ...  0.08558145  0.03705371
   0.11568356]]
Kevin John Ryan (born 20 June 1984) is an Irish actor, known for his television roles in the TV series Copper and Crossbones.
[[-0.02874381  0.10000181  0.2356828  ...  0.1370204   0.09122743
   0.09478533]]
Sir Arthur Campbell Rymill (8 December 1907 – 27 March 1989) was a b

[[-0.00519743  0.10680354  0.12630084 ...  0.03382147  0.0739223
   0.04958379]]
Antonio Zappia (born 13 June 1952) is an Australian politician and former powerlifting champion.
[[0.01024176 0.08429751 0.15794462 ... 0.03074836 0.0394147  0.05121687]]
Paul Regan Adams (born 20 January 1977) is a former South African cricketer.
[[-0.01312288  0.0900583   0.20340604 ...  0.07938757  0.03795533
   0.07059093]]
Inatio Akaruru CBE (31 March 1937 – 31 January 2014) was a Cook Islands politician, Cabinet Minister and Deputy Prime Minister.
[[0.0753592  0.04943122 0.20363668 ... 0.06575292 0.15284145 0.15586525]]
Eric Cameron Armishaw (1906 – 30 May 1971) was a New Zealand local-body politician and boxing referee.
[[0.01740709 0.09449054 0.12933452 ... 0.07604551 0.06433039 0.09502506]]
Tommy Armstrong Jr. (born November 8, 1993) is an American football quarterback for Sioux Falls Storm of the Indoor Football League (IFL).
[[0.03174324 0.13327655 0.16250138 ... 0.08815113 0.05000255 0.07393596

[[-0.01807702  0.07226838  0.16327362 ...  0.0493938   0.04261024
   0.10719024]]
Colonel Arthur Espie Porritt, Baron Porritt,  (10 August 1900 – 1 January 1994) was a New Zealand physician, military surgeon, statesman and athlete.
[[0.00578941 0.04943122 0.12918545 ... 0.04487365 0.09911086 0.09906054]]
Theodorus Jacobus Leonardus "Dick" Quax (1 January 1948 – 28 May 2018) was a Dutch-born New Zealand runner, one-time world record holder in the 5000 metres, and local-body politician.
[[0.00079854 0.14072578 0.14819935 ... 0.10943598 0.04859019 0.10341408]]
Paul Quinn College (PQC) is a private historically black Methodist college in Dallas, Texas.
[[-0.01312288  0.05339834  0.03124345 ...  0.05308102  0.03369996
   0.06938932]]
William Lee Rees (16 December 1836 – 18 May 1912) was an English-born New Zealand cricketer, politician and lawyer.
[[-0.02874381  0.04943122  0.16267824 ...  0.0058507   0.09047449
   0.08504023]]
Ben Sandford (born 12 March 1979 in Rotorua) is a New Zealand s

[[0.01190357 0.04943122 0.10578334 ... 0.04951847 0.05583615 0.07279273]]
Donald Ray Lash (August 15, 1912 – September 19, 1994) was an American long-distance runner who won 12 national titles from 1934 to 1940, including seven consecutive men's national cross-country championships, and who set a world's record for the two-mile run in 1936.
[[0.00382293 0.1955309  0.15397118 ... 0.05823573 0.09293866 0.10860557]]
Charles Thomas McMillen (born May 26, 1952) is a retired professional basketball player, Rhodes Scholar, and Democratic U.S. Ralph Harold Metcalfe Sr. (May 29, 1910 – October 10, 1978) was an American track and field sprinter and politician.
[[-0.00519743  0.15429512  0.1733776  ...  0.05693707  0.07920743
   0.10360759]]
Larry Jack Mildren (October 10, 1949 – May 22, 2008), was an All-American quarterback at the University of Oklahoma, and professional football player with the Baltimore Colts and New England Patriots.
[[0.00596439 0.10710664 0.22954565 ... 0.04148607 0.088182

[[-0.02874381  0.19396026  0.11650616 ...  0.09768764  0.08189334
   0.09111338]]


In [24]:
#Load test questions dataset
import pandas as pd
df = pd.read_csv('questions.csv')

In [25]:
questions = list(df["question"])

In [26]:
len(questions)

401

In [27]:
for i in range(len(questions)):
    print(i)
    dict_embeddings[questions[i]] = infersent.encode([questions[i]], tokenize=True)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [28]:
#View Sentence Vector for this query
dict_embeddings['Who is the 45th and current president of the United States?'][0]

array([-0.02042911,  0.06372681,  0.10245018, ..., -0.00508549,
        0.01406335,  0.10593148], dtype=float32)

In [29]:
#Create two dictionaries based on even and odd number of entries
d1 = {key:dict_embeddings[key] for i, key in enumerate(dict_embeddings) if i % 2 == 0}
d2 = {key:dict_embeddings[key] for i, key in enumerate(dict_embeddings) if i % 2 == 1}

In [30]:
d1

{'Barack Hussein Obama II ( (listen); born August 4, 1961) is an American politician and attorney who served as the 44th president of the United States from 2009 to 2017.': array([[-0.02874381,  0.04943122,  0.20910737, ...,  0.1316887 ,
          0.04436744,  0.11170954]], dtype=float32),
 'George Walker Bush (born July 6, 1946) is an American politician and businessman who served as the 43rd president of the United States from 2001 to 2009.': array([[-0.02874381,  0.04943122,  0.16229874, ...,  0.06349707,
          0.054673  ,  0.1077443 ]], dtype=float32),
 'George Washington (February 22, 1732 – December 14, 1799) was an American political leader, military general, statesman, and Founding Father who served as the first president of the United States from 1789 to 1797.': array([[-0.02874381,  0.04943122,  0.1495678 , ...,  0.03927369,
          0.13337407,  0.114299  ]], dtype=float32),
 'John Fitzgerald Kennedy (May 29, 1917 – November 22, 1963), often referred to by his initials 

In [31]:
d2

{'Joseph Robinette Biden Jr. (; born November 20, 1942) is an American politician who served as the 47th vice president of the United States from 2009 to 2017 and represented Delaware in the U.S. Senate from 1973 to 2009.': array([[0.01917268, 0.05178139, 0.21973753, ..., 0.06421494, 0.0845053 ,
         0.11733628]], dtype=float32),
 'Donald John Trump (born June 14, 1946) is the 45th and current president of the United States.': array([[-0.01994209,  0.06318004,  0.1411632 , ...,  0.02324948,
          0.08776435,  0.09802058]], dtype=float32),
 'Thomas Jefferson (April 13, 1743 – July 4, 1826) was an American statesman, diplomat, lawyer, architect, philosopher, and Founding Father who served as the third president of the United States from 1801 to 1809.': array([[-0.02874381,  0.04943122,  0.09886527, ...,  0.03141018,
          0.14112839,  0.11247957]], dtype=float32),
 'Theodore  Roosevelt Jr. ( ROH-zə-velt; October 27, 1858 – January 6, 1919) was an American statesman, politicia

In [32]:
#Dump dictionary
with open('data/dict_embeddings1.pickle', 'wb') as handle:
    pickle.dump(d1, handle)

In [33]:
#Dump dictionary
with open('data/dict_embeddings2.pickle', 'wb') as handle:
    pickle.dump(d2, handle)